-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3307
-- Généré le : ven. 10 déc. 2021 à 10:29
-- Version du serveur :  10.4.13-MariaDB
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `enjoyvoyage`
--

-- --------------------------------------------------------

--
-- Structure de la table `hotel`
--

DROP TABLE IF EXISTS `hotel`;
CREATE TABLE IF NOT EXISTS `hotel` (
  `id_hotel` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(100) NOT NULL,
  `ville` varchar(100) NOT NULL,
  `pays` varchar(100) NOT NULL,
  `description` varchar(10000) NOT NULL,
  `prix` double(11,2) DEFAULT NULL,
  `photo` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`id_hotel`)
) ENGINE=InnoDB AUTO_INCREMENT=120 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `hotel`
--

INSERT INTO `hotel` (`id_hotel`, `nom`, `ville`, `pays`, `description`, `prix`, `photo`) VALUES
(1, 'Ibis Paris', 'Paris', 'France', 'Découvrez pourquoi l\'Ibis Paris Place D\'italie 13ème est l\'hôtel préféré des voyageurs visitant Paris. Offrant un grand confort et un excellent rapport qualité-prix, il propose un cadre une familial et un large éventail de services conçus pour les voyageurs comme vous.Tout proche de monuments populaires comme Cathédrale Notre-Dame de Paris (2,4 km) et Quartier Latin (2,4 km), l\'Ibis Paris Place d\'Italie 13eme vous permet de profiter facilement des attractions les plus connues de Paris.Les chambres sont équipées d\'une télévision à écran plat et d\'une climatisation. Le wi-fi gratuit vous permet également de vous relaxer en restant connecté.', 74.65, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/d6/86/61/exterior-view.jpg?w=900&h=-1&s=1'),
(32, 'L\'Imprimerie Hôtel', 'Paris', 'France', 'Situé à Clichy, à 10 minutes à pied de Paris, l\'établissement L\'Imprimerie Hôtel propose un sauna, une salle de sport, une terrasse et une connexion Wi-Fi gratuite. Les chambres de l\'établissement L\'Imprimerie Hôtel comprennent une salle de bains privative, un sèche-cheveux, un coffre-fort, une télévision par satellite et un bureau. Les chambres supérieures, exécutives et deluxe sont pourvues de peignoirs et de chaussons. Un petit-déjeuner buffet est servi chaque matin. Vous apprécierez une boisson sur le toit-terrasse. L\'Imprimerie Hôtel comporte également une bagagerie gratuite et 3 salles de conférence.', 76.50, 'https://q-xx.bstatic.com/xdata/images/hotel/max500/147123617.jpg?k=1919c01faa7b8b5b1b10367c5fca7e248ee9b29a0f6d45fdf4db0bbc60b32bfb&o='),
(33, 'YAYS Paris Issy', 'Paris', 'France', 'Le YAYS Paris Issy propose des hébergements climatisés à Issy-les-Moulineaux, à 700 mètres du musée français de la carte à jouer, à 1,3 km du stade Robert-Charpentier et à moins de 1 km du siège de Canal+. Une connexion Wi-Fi gratuite est disponible dans l’ensemble des locaux. Vous bénéficierez également d’un espace de stationnement privé sur place. Dotés de parquet, les logements comprennent un coin repas, une télévision par câble à écran plat, une cuisine entièrement équipée avec un lave-vaisselle ainsi qu’une salle de bains privative pourvue d’une douche et d’un sèche-cheveux. Un four, un micro-ondes, un réfrigérateur, une bouilloire et une machine à café sont à votre disposition. L\'appart\'hôtel possède une terrasse et assure un service de livraison de nourriture. Les sites d\'intérêt à proximité du YAYS Paris Issy incluent les sièges d\'Eurosport, de Coca Cola France et de France 24. L’aéroport de Paris-Orly, le plus proche, vous attend à 16 km.\r\n', 68.30, 'https://q-xx.bstatic.com/xdata/images/hotel/max500/242359890.jpg?k=3bca08ac565170e1a5d0e07223325f487b4467aa706ad83ecf6cdea7058a6d6d&o='),
(34, 'Mijo\'s Appartements Hôtel', 'Paris', 'France', 'Situé à Fontenay-sous-Bois, en Île-de-France, le Mijo\'s Appartements Hôtel propose des hébergements avec connexion Wi-Fi gratuite. Revêtus de parquet, les logements comprennent une télévision par satellite à écran plat ainsi qu\'une salle de bains privative pourvue d\'une douche et d\'un sèche-cheveux. Un réfrigérateur, un minibar, des plaques de cuisson, une bouilloire et une machine à café sont également fournis. Cet appart\'hôtel sert un petit-déjeuner à la carte. Vous séjournerez à 10 km de Paris et à 38 km de Chantilly. L\'aéroport de Paris-Orly, le plus proche, est à 16 km.', 50.00, 'https://q-xx.bstatic.com/xdata/images/hotel/max500/289255853.jpg?k=3d04c7be05489712a38e25356f63f676cc4268b9905d637d73204093aa0612bc&o='),
(35, 'B&B Hotel Saint-Denis Porte De Paris', 'Paris', 'France', 'Général\r\nÀ proximité de Stade de France\r\nEmplacement\r\nSaint-Denis ne manque pas de choses à découvrir ; B&B Hotel Saint-Denis Porte De Paris vous fait profiter d\'un séjour non loin de l\'aéroport et se trouve à 2 min en voiture de Stade de France et à 7 minutes de Zénith de Paris. Cet hôtel se trouve à 9 km de La Machine du Moulin Rouge et à 9,5 km de Musée Grévin.\r\nRestaurant\r\nUn petit déjeuner buffet est servi en semaine de 06 h 30 à 10 h 00 et le week-end de 07 h 30 à 10 h 30 (en supplément).\r\n', 44.00, 'https://res.cloudinary.com/lastminute/image/upload/q_auto/v1632661102/o4wsasoiz37aecekg6um.jpg'),
(36, 'Mercure Paris La Défense', 'Paris', 'France', 'Général\r\nLe Mercure Paris La Défense est situé dans le quartier des affaires de La Défense, à seulement 10 minutes en métro du centre de Paris. Le stade U Arena se trouve à 10 minutes de route de l’hôtel. Les chambres disposent de la climatisation, d’une télévision par satellite à écran plat et d’un plateau de courtoisie. Certaines comprennent une machine à café Nespresso et un minibar avec des boissons sans alcool gratuites. L’établissement propose une connexion Wi-Fi gratuite et illimitée, ainsi qu’une navette entre l\'hôtel et la station de métro Grande Arche de la Défense. Vous pourrez profiter de la salle de sport ou du hammam, puis vous détendre au bar sur place. Le restaurant VINGKO sert une cuisine française traditionnelle. Le Mercure Paris La Défense possède également des salles de réunions et un centre d’affaires. Vous séjournerez à seulement 16 minutes à pied du Centre des nouvelles industries et technologies', 44.00, 'https://q-xx.bstatic.com/xdata/images/hotel/max500/115176452.jpg?k=7d7f67ad1b5d4d15e0d8f1acd2f4d32c63fc75814b9f088acd59816babeb8412&o='),
(37, 'Rraser Suites Harmonie', 'Paris', 'France', 'Général\r\nSitué dans le quartier des affaires de Paris, l\'établissement Fraser Suites Harmonie Paris La Défense se trouve à proximité des rives de la Seine. Une connexion Wi-Fi gratuite et un parking sous-terrain privé sont proposés sur place. Le centre-ville de Neuilly-sur-Seine se trouve à 1,6 km, et le stade U Arena est à 11 minutes en voiture. Les suites du Fraser Suites Harmonie Paris La Défense sont équipées d\'un coin salon indépendant pourvu d\'une télévision à écran plat, d\'un lecteur DVD et d\'un centre multimédia. Toutes possèdent un micro-ondes et un réfrigérateur, et certaines bénéficient d\'un balcon offrant une vue sur les environs. Le Fraser Suites sert tous les matins un petit-déjeuner buffet composé de viennoiseries chaudes. Vous pourrez prendre un verre au bar sur place. La station de métro Esplanade de la Défense, à 5 minutes à pied, dessert directement les sites touristiques de la capitale. La place de la Concorde et l\'avenue des Champs-Élysées sont à moins de 8 minutes en métro.', 118.00, 'https://q-xx.bstatic.com/xdata/images/hotel/max500/143720534.jpg?k=13cb2ef64f81c7057faebc4aa5fadc0a9ec83a9251bc86e848c72f2a85c5b5c8&o='),
(38, 'Hotel Lille Europe', 'Lille', 'France', 'Vous pouvez bénéficier d\'une réduction Genius dans l\'établissement Hotel Lille Europe ! Connectez-vous pour économiser.\r\n\r\nL\'Hotel Lille Europe est un établissement 3 étoiles situé au cœur du quartier des affaires international, à seulement 250 mètres de la gare de Lille-Flandres et à 17 minutes de route du stade Pierre-Mauroy. Il propose une réception ouverte 24h/24 et une connexion Internet gratuite.\r\n\r\nPrésentant une décoration colorée, les chambres sont insonorisées et disposent d\'une télévision par câble. Leur salle de bains privative est pourvue d\'un sèche-cheveux. Toutes les chambres sont desservies par un ascenseur.\r\n\r\nUn petit-déjeuner buffet est servi tous les matins dans la salle prévue à cet effet. Cette dernière est dotée d\'un micro-ondes et d\'une vue panoramique sur les environs', 56.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/244582029.jpg?k=75402fca188876601d06b7d0c7a2742133ca3d850979d6e0d489c87610337f45&o=&hp=1'),
(39, 'ibis Styles', 'Lille', 'France', 'L’ibis Styles Lille Centre Gare Beffroi est situé dans le centre-ville de Lille, à 600 mètres des gares de Lille-Flandres et de Lille-Europe. Le centre des congrès Lille Grand Palais et le complexe Nouveau Siècle se trouvent à 1 km.\r\n\r\nToutes les chambres comprennent une télévision à écran plat, une connexion Wi-Fi gratuite et une salle d’eau privative.', 58.00, 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/251753805.jpg?k=8c8182584c5a1cdbbcd7e880fc6cab8a5bca3fb8cacc9b356d416194d6ec6eb8&o=&hp=1'),
(40, 'Holiday Inn Express ', 'Lille', 'France', 'L\'Holiday Inn Express Lille Centre est situé dans le centre de Lille, à 350 mètres du Palais des Beaux Arts et à 9 km du stade Pierre Mauroy. Vous séjournerez à 900 mètres du centre de conventions Le Nouveau Siècle et à 2 km de Lille Grand Palais.\r\n\r\nLes chambres de l\'Holiday Inn Express Lille Centre sont équipées d\'une télévision à écran plat, d\'un téléphone, d\'un sèche-cheveux et d\'un plateau/bouilloire. Elles sont toutes desservies par un ascenseur. Vous bénéficierez gratuitement d\'une connexion Wi-Fi.\r\n\r\nUn petit-déjeuner buffet est servi tous les matins.', 80.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/318036451.jpg?k=bdc5e7195148b2054b4b5665a1e8b513c3559318f9c29e94f1c84cf82d6b89d0&o=&hp=1'),
(41, 'Eklo Hotels', 'Lille', 'France', 'Doté d\'une terrasse, l\'Eklo Hotels Lille est situé à Lille dans le Nord-Pas-de-Calais, à 2 km du Zénith. Vous séjournerez à 2,6 km de Lille Flandres et à 2,7 km de Lille Europe.\r\nLes chambres disposent d\'une salle de bains privative. Les autres prestations (comme les articles de toilette et le départ tardif) entraînent des frais supplémentaires.\r\nUn bar et une réception ouverte 24h/24 sont présents. Le restaurant Barbapizz\' prépare des pizzas et des salades. Un petit-déjeuner continental en libre-service est servi tous les jours moyennant un supplément.', 20.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/170779838.jpg?k=d484bf939b171d9d8380bf8951fb4213f4341c8d3c02ca03b61a7e53371aefcd&o=&hp=1'),
(42, 'Grand Hotel Bellevue', 'Lille', 'France', 'Vous pouvez bénéficier d\'une réduction Genius dans l\'établissement Grand Hotel Bellevue - Grand Place ! Connectez-vous pour économiser.\r\n\r\nSitué sur la Grand-Place, dans le Vieux-Lille, le Grand Hotel Bellevue - Grand Place occupe un bâtiment à l\'architecture flamande. Ses chambres disposent d\'une salle de bains en marbre et de mobilier d\'époque. La station de métro Rihour est accessible à 100 mètres. Vous pourrez rejoindre le centre de conventions Le Nouveau Siècle en 2 minutes à pied et le Lille Grand Palais se trouve à 1,4 km.', 100.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/251516857.jpg?k=5ab28ad9527c12592c4682494c0d92d9f4a82ae793a18f5d8d4934464712a35b&o=&hp=1'),
(43, 'ibis Styles', 'Nantes', 'France', '’ibis Styles Lille Centre Gare Beffroi est situé dans le centre-ville de Lille, à 600 mètres des gares de Lille-Flandres et de Lille-Europe. Le centre des congrès Lille Grand Palais et le complexe Nouveau Siècle se trouvent à 1 km.\r\n\r\nToutes les chambres comprennent une télévision à écran plat, une connexion Wi-Fi gratuite et une salle d’eau privative.\r\n\r\nChaque matin, le petit-déjeuner vous sera servi. Vous pourrez vous détendre avec une boisson dans le bar sur place. Des événements d’entreprise peuvent être organisés dans les 3 salles de réunion modernes.\r\n\r\nLe quartier commerçant et d’affaires Euralille se trouve à 10 minutes de marche. Le stade Pierre-Mauroy est accessible en 15 minutes de route.\r\n', 76.50, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/119905379.jpg?k=6445ab1d24b56b6a01e2e307d95b31b3b0ba3dc53b530385b065f2de71f02ded&o=&hp=1'),
(44, 'Radisson BLU Hotel ', 'Nantes', 'France', 'Le Radisson BLU Hotel Nantes est situé en centre-ville, à seulement 1,3 km de la Loire. Il assure un service d\'étage 24h/24.\r\n\r\nLes chambres sont décorées dans un style personnalisé avec un mobilier signé Jean-Philippe Nuel. Elles comprennent une salle de bains privative, une télévision à écran plat et une connexion Wi-Fi gratuite.\r\n\r\nLe Radisson BLU Hotel Nantes sert un petit-déjeuner tous les matins, que vous pourrez également déguster en chambre. Au restaurant, vous savourerez une cuisine traditionnelle rehaussée d\'une touche de modernité. De plus, vous profiterez d\'un bar ouvert tous les jours.', 110.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/158375722.jpg?k=af91f501c2278fd272a19c3b80201e1c0def3d97c8c43ec6457402dc251f7af1&o=&hp=1'),
(45, 'Maisons du Monde Hotel & Suites', 'Nantes', 'France', 'Situé dans le centre-ville de Nantes, à côté d\'arrêts de bus et de tramway locaux ainsi qu\'à 2 km de la gare TGV, l\'établissement Maisons du Monde Hotel & Suites - Nantes propose des hébergements insonorisés avec télévision par satellite à écran plat.\r\n\r\nToutes les chambres sont desservies par un ascenseur et comprennent un bureau, du matériel de repassage ainsi qu\'une salle de bains privative.', 100.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/176902089.jpg?k=b11acfca3854727fea0ca268db5c96ed43e82ccc769bd234ba02a94eafd5d0a4&o=&hp=1'),
(46, 'ibis Nantes Centre Gare Sud ', 'Nantes', 'France', 'L\'ibis Nantes Centre Gare Sud est situé en face du château des ducs de Bretagne, dans le centre-ville, à seulement 300 mètres de la gare SNCF. Il propose une réception ouverte 24h/24, une connexion Wi-Fi gratuite, un restaurant international, un bar et une terrasse.\r\n\r\nLes chambres climatisées de l\'ibis Nantes Centre Gare Sud comprennent une télévision par satellite à écran LCD et un téléphone. Leur salle de bains est pourvue d\'articles de toilette gratuits.\r\n\r\nChaque jour, vous savourerez un petit-déjeuner buffet composé de plats sucrés et salés, tels que des œufs, de la salade de fruits, des yaourts et des jus de fruits. Des viennoiseries cuites sur place et des madeleines françaises fraîches sont aussi proposées, ainsi qu\'une boisson chaude et un fruit à emporter. En dehors des heures régulières de petit-déjeuner, vous pourrez également profiter d\'une option plus légère, à partir de 4h00. L\'établissement possède un restaurant ibis Kitchen préparant des plats français à la carte et des plateaux-repas.', 58.00, 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/257306345.jpg?k=002f64ea9b461b55cbdba4ee10c2e9b955553bd7b16da52b5e4bc82afefe3f3a&o=&hp=1'),
(47, 'Hotel Le Petit Duquesne ', 'Nantes', 'France', 'Situé dans le centre-ville de Nantes, l\'Hotel Le Petit Duquesne propose des chambres dotées d\'une connexion Wi-Fi gratuite. Vous séjournerez à proximité du tramway, à 5 minutes de marche de la navette aéroport et de la gare centrale de Nantes.\r\n\r\nLes chambres de l\'Hotel Le Petit Duquesne sont insonorisées et disposent d\'une télévision à écran plat ainsi que d\'une salle de bains privative.\r\n\r\nUn petit-déjeuner buffet est servi chaque matin à l\'Hotel Le Petit Duquesne.', 47.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/140262820.jpg?k=3dcfb0440eb0c0b3eecaf45961f03eb0df1b376d8f12629f1df60b20197e8853&o=&hp=1'),
(48, 'Okko Hotels Nantes Château', 'Nantes', 'France', 'Situé dans le centre-ville de Nantes, à seulement 900 mètres de la gare et du parc des expositions, l’Okko Hotels Nantes Château propose une réception ouverte 24h/24 et une connexion Wi-Fi gratuite. L\'établissement dispose de 12 places de stationnement privées payantes et attribuées sous réserve de disponibilité. Merci de contacter l\'établissement pour vérifier leur disponibilité.\r\n\r\nDécorées dans un style moderne, les chambres sont climatisées et équipées d’une télévision par satellite, d’un coffre-fort et d’une station d\'accueil pour iPod. Toutes les chambres comportent une machine à café et une salle de bains privative pourvue d’articles de toilette et d’un sèche-cheveux.\r\n', 100.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/26253602.jpg?k=1ba9bc361a21297cc5aac87eb4078b3e6b0c5178111f26d76b229b4475cf2c33&o=&hp=1'),
(49, 'Hôtel Amiral ', 'Nantes', 'France', 'L\'Hôtel Amiral possède une connexion Wi-Fi gratuite dans le centre-ville de Nantes, à 95 mètres du théâtre Graslin. Il a reçu le label écologique international Clef Verte.\r\n\r\nLes chambres insonorisées de l\'Hôtel Amiral sont équipées de la télévision par satellite et d\'un minibar. Leur salle de bains est pourvue de systèmes respectueux de l\'environnement.\r\n\r\nTous les jours, l\'Hôtel Amiral sert un petit-déjeuner buffet que vous pourrez prendre dans la salle à manger ou dans le confort de votre chambre. Le soir, un service d\'étage est assuré.', 76.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/298793973.jpg?k=d3215f3fbbb74de4185be1355c6f280f52ce0bd1821f1ffec53a8ef60389220e&o=&hp=1'),
(50, 'ibis budget ', 'Toulouse', 'France', 'Situé dans le centre-ville de Toulouse, à 8 km de l\'aéroport de Toulouse Blagnac et à 6 km du stade de Toulouse, l\'ibis budget Toulouse Centre possède une réception ouverte 24h/24, une connexion Wi-Fi et un parking gratuits ainsi que des chambres insonorisées.\r\n\r\nToutes les chambres climatisées de l\'ibis Budget Toulouse Centre disposent d\'une salle de bains privative avec douche et toilettes, d\'une armoire ainsi que d\'une télévision à écran plat.\r\n\r\nChaque matin, vous pourrez déguster un petit-déjeuner buffet dans la salle à manger ou sur la terrasse. Il comprend des croissants frais, un large choix de pains, des céréales, de brioches, de pâtes à tartiner, de confitures, de miel, de salade de fruits frais, de yaourts, de fromages, de boissons chaudes et de jus de fruits.', 44.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/86677137.jpg?k=41065056e5daf749643849764d5e38506f2e53afafda69c3c464184400e35b77&o=&hp=1'),
(51, 'Hotel Ours Blanc - Place Victor Hugo ', 'Toulouse', 'France', 'Situé en plein cœur de Toulouse, l\'Hotel Ours Blanc - Place Victor Hugo est situé à côté de la place Victor Hugo, à 4 km du stade.\r\n\r\nToutes les chambres sont insonorisées. Elles sont munis d\'une connexion Wi-Fi gratuite, de la climatisation et d\'une télévision.\r\n\r\nUn petit-déjeuner buffet est servi sur place. Des journaux gratuits sont à votre disposition dans la salle à manger.\r\n\r\nL\'Hotel Ours Blanc se trouve à 200 mètres des stations de métro Jeanne d\'Arc et Capitole. Vous séjournerez à proximité du canal du Midi, de la place du Capitole et du marché Victor Hugo.\r\nC\'est le quartier préféré des voyageurs visitant Toulouse, selon les commentaires clients indépendants.\r\n', 44.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/259722458.jpg?k=78f66b3f2bb67e6311c7b4b1acf4999d765a75877aa0123e78d63d5e9d02b7d8&o=&hp=1'),
(52, 'Premiere Classe', 'Toulouse', 'France', 'Cet hôtel Première Classe est situé à côté de l\'autoroute A620 et du lac de Sesquières, à seulement 5 km au nord du centre de Toulouse. Il propose un hébergement avec salle de bains et un parking privé gratuit sur place.\r\n\r\nChaque chambre de l\'hôtel Première Classe Toulouse Sesquières dispose d\'une salle de bains privative et d\'une télévision.\r\n\r\nL\'Hôtel Toulouse Sesquières abrite une réception ouverte 24h/24. La station de métro La Vache se trouve à 2,5 km et permet de rejoindre le centre-ville et la gare de Toulouse Matabiau.', 42.00, 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/20846011.jpg?k=5db72a8155baf4b6d9d799ca77473a4204df5214e631ee8fe39785ed5b767a47&o=&hp=1'),
(53, 'Odalys City Toulouse', 'Toulouse', 'France', 'Situé dans le centre-ville de Toulouse, à 8 km de l\'aéroport de Toulouse Blagnac et à 6 km du stade de Toulouse, l\'ibis budget Toulouse Centre possède une réception ouverte 24h/24, une connexion Wi-Fi et un parking gratuits ainsi que des chambres insonorisées.\r\n\r\nSitué à 1,8 km du Zénith de Toulouse, l\'Odalys City Centre Compans Caffarelli propose un salon commun, un jardin et une réception ouverte 24h/24.\r\n\r\nLes logements climatisés comprennent une télévision par satellite à écran plat, une cuisine entièrement équipée avec un coin repas et une salle de bains privative pourvue d\'un sèche-cheveux. Un lave-vaisselle, un micro-ondes, un réfrigérateur et une bouilloire sont également fournis.\r\n\r\nCet appart\'hôtel sert un petit-déjeuner buffet ou continental.\r\n', 76.00, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/327619078.jpg?k=1e56d4c194104118ea63a9fa301fcfb16b0ea0298eebde1be019d6aa7af07a5f&o=&hp=1'),
(54, 'Hotel Le Père Léon', 'Toulouse', 'France', 'Situé place Esquirol au centre ville de Toulouse, l’Hôtel Le Père Léon, enseigne emblématique et familiale de la Ville rose depuis 1905, jouit d’un excellent emplacement dans le cœur historique et culturel de la ville et tout proche des rues commerçantes les plus attractives. Au cœur du « Vieux Toulouse », et entièrement rénové après 2 ans de travaux, Le Père Léon est le point de départ rêvé pour découvrir les incontournables de Toulouse comme la Place du Capitole, les rues pittoresques chargées d’histoire, la Garonne, la Cité de l’Espace, les musées, théâtres …', 91.00, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/14/57/7d/lobby-view.jpg?w=800&h=-1&s=1'),
(55, 'Hotel NH', 'Nice', 'France', 'Situé à proximité de la vieille ville, l\'hôtel Hotel NH Nice est un établissement quatre étoiles avec piscine sur le toit, idéal pour profiter de Nice en toute décontraction. Les 152 chambres de l\'établissement sont dotées du Wi-Fi gratuit, de la climatisation, d\'un coffre-fort, d\'un minibar, d\'une télévision par satellite et d\'une salle de bains avec sèche-cheveux et baignoire. L\'hôtel possède une salle de sport, un sauna, une terrasse sur le toit avec piscine, trois salles de réunion, ainsi qu\'un parking privé. L\'hôtel Hotel NH Nice dispose d\'un restaurant, L\'Oliveraie, qui sert une cuisine méditerranéenne, ainsi que d\'un bar ouvert sur la terrasse en été.', 76.00, 'https://imgcy.trivago.com/c_fill,d_dummy.jpeg,f_auto,h_190,q_auto,w_240/partnerimages/22/86/228624036.jpeg'),
(56, '66 Nice', 'Nice', 'France', 'Profitez des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit et un service de concierge.Lors de votre séjour dans cet hôtel, vous pourrez prendre vos repas dans votre chambre grâce au service d\'étage 24 heures sur 24. Un petit déjeuner buffet est servi tous les jours de 07 h 00 à 11 h 00 moyennant un supplément.Le classement officiel par étoiles de cet établissement a été attribué par ATOUT France, l\'agence de développement touristique de la France.Les équipements et services proposés incluent un centre d\'affaires, un service de nettoyage à sec / blanchisserie et une réception ouverte 24 heures sur 24. ', 69.00, 'https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_1300,q_auto,w_2000/partnerimages/72/76/727673722.jpeg'),
(58, 'Le Negresco', 'Nice', 'France', 'Doté d\'une situation idyllique face à la mer et sur la Promenade des Anglais, l\'hôtel Le Negresco est un établissement cinq étoiles luxueux et emblématique de l\'histoire de Nice. L\'établissement possède différents types de chambres doubles et de suites, certaines avec vue sur la mer. Elle sont toutes climatisées, et comprennent une télévision et du mobilier d\'époque.', 236.00, 'https://imgcy.trivago.com/c_fill,d_dummy.jpeg,f_auto,h_190,q_auto,w_240/uploadimages/18/71/18716182.jpeg'),
(59, 'B&B Hotel Nice Aéroport Arenas', 'Nice', 'France', 'Bienvenue dans notre B&B HOTEL Nice Aéroport Arenas! Vous cherchez un hôtel abordable et bien situé ? Notre hôtel 3 étoiles, situé à 5 minutes des plages, de la promenade des anglais, de l’aéroport International de Nice Côte d\'Azur ou encore du Vieux Nice (centre-ville), sera votre meilleur choix ! Notre hôtel est ouvert 24/24 toute l\'année et dispose de 167 chambres entièrement équipées et climatisées, avec une décoration moderne, une salle de bain privée et une connexion Internet Wi-Fi haut débit', 52.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/23/52/23528116_v2.jpeg'),
(60, 'Hôtel Mercure Nice Centre Notre-Dame', 'Nice', 'France', 'L\'hôtel Hôtel Mercure Nice Centre Notre-Dame est un établissement 4 étoiles situé à seulement six minutes de marche de la gare de Nice Ville. L\'hôtel dispose de 198 chambres climatisées. Elles sont équipées d\'une salle de bains avec douche ou baignoire, d\'une télévision à écran plat, d\'un coffre-fort, d\'un minibar et d\'un plateau de courtoisie. Le Hôtel Mercure Nice Centre Notre-Dame offre de belles prestations propices à la détente : un toit-terrasse avec une vue à 360 degrés sur Nice et une piscine, un espace fitness et bains à remous, ainsi que des terrasses avec coins \"cocooning\". De plus, l\'hôtel dispose d\'un jardin privatif. Une salle de réunion est également accessible.', 95.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/50/12/50128_v8.jpeg'),
(61, 'Best Western Plus Hotel Massena', 'Nice', 'France', 'Hôtel 4 étoiles de caractère à la façade Belle Époque et au décor design, le Best Western Plus Hotel Massena Nice se trouve au cœur du centre-ville de Nice. Les 110 chambres et suites de l\'hôtel sont équipées d\'une literie haut de gamme. Elles disposent du Wi-Fi gratuit, de la climatisation, d\'une télévision à écran plat, d\'un minibar, d\'un plateau de courtoisie, d\'un coffre-fort et, pour certaines, d\'un balcon avec vue sur la ville', 99.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/11/56/11565_v10.jpeg'),
(62, 'Hôtel de Paris Monte-Carlo', 'monaco', 'Monaco', 'Bâti en 1864, ce palace mythique est idéalement situé sur la Place du Casino, au cœur de la Principauté de Monaco. Incontournable pour des séjours d’exception et des événements de haut niveau, l’hôtel est également un haut lieu de la gastronomie, réputé pour son art de vivre avec ses 3 prestigieux restaurants, dont le célèbre Louis XV - Alain Ducasse et Le Grill. Une expérience au parfum unique, sur les traces des grands de ce monde.\r\n', 725.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/42/32/42327_v7.jpeg'),
(63, 'Fairmont Monte Carlo', 'monaco', 'Monaco', 'Merveilleusement situé entre le célèbre Casino et la mer Méditerranée, le Fairmont Monte Carlo est un luxueux établissement 4 étoiles, situé au cœur de la principauté et face au célèbre virage en épingle du circuit de Formule 1. Les 596 chambres et suites sont équipées de la climatisation, d\'un espace bureau, d\'un téléviseur avec technologie Chromecast, d\'un coffre-fort, d\'un mini-bar, d\'une machine à café et d’une terrasse privée mobilier. Les salles-de-bains sont en marbre et disposent d\'articles de toilettes de luxe, d\'un sèche-cheveux, de peignoirs et pantoufles. ', 263.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//partnerimages/60/77/607700318.jpeg'),
(64, 'Hotel Novotel Monte Carlo', 'monaco', 'Monaco', 'Rénové dans un esprit Riviera, le Novotel Monte-Carlo vous accueille au cœur de Monaco. L\'hôtel dispose d\'un restaurant avec terrasse, d\'un bar, d\'une piscine, de 12 salles de réunion et d\'un parking payant. Wifi offert dans tout l\'hôtel.', 206.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/15/89/158923_v9.jpeg'),
(65, 'Le Méridien Beach Plaza', 'monaco', 'Monaco', 'Détendez-vous sur la plage privée et profitez des nombreuses infrastructures de loisirs proposées par l\'établissement, notamment un centre de remise en forme et une piscine couverte. Parmi les services et équipements offerts par cet hôtel vous trouvez également l\'accès Wi-Fi à Internet gratuit, un service de concierge et un service de garde d\'enfants payant.Prenez un délicieux repas au restaurant et comblez tous vos petits creux en profitant du service d\'étage 24 heures sur 24 proposé par cet hôtel.', 260.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/16/11/16119_v3.jpeg'),
(66, 'Hotel Columbus Monte Carlo', 'monaco', 'Monaco', 'Entièrement rénové en 2018, ce boutique hôtel 3* est doté d\'une piscine extérieure chauffée, ouverte en saison (Avril - Octobre) avec une terrasse bordée de palmiers. L\'hôtel Columbus Monte Carlo offre des magnifiques vues sur la Méditerranée, la roseraie Princesse Grace et les montagnes. \r\n\r\nToutes nos chambres (rénovées en 2018) bénéficient des équipements suivants : TV HD écrans plats avec option d’écran miroir, accès rapide WIFI gratuit, machine Nespresso et bouilloire (thé, café), fer et planche à repasser, sèche-cheveux, éclairage variable, prises électriques USB, coffre-fort avec chargeur intégré, produits de toilette Elemis, baignoire, minibar. ', 190.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/42/32/42320_v9.jpeg'),
(67, 'NH Brussels EU Berlaymont', 'Bruxelles', 'Belgique', 'Situé à proximité du Quartier Européen, l\'hôtel NH Brussels EU Berlaymont est un établissement quatre étoiles confortable, pratique pour un séjour bruxellois. Les 214 chambres de l\'établissement sont dotées de la climatisation, d\'une télévision, d\'une machine à café, d\'une bouilloire électrique et d\'une terrasse. L\'hôtel NH Brussels EU Berlaymont propose une connexion Wi-Fi gratuite dans tout l\'établissement, ainsi qu\'un centre sportif, des salles de conférence, un parking couvert et des services de blanchisserie', 95.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/54/74/54743_v13.jpeg'),
(68, 'nhow Brussels Bloom', 'Bruxelles', 'Belgique', 'Arborant 4 étoiles, l\'hôtel nhow Brussels Bloom est un établissement décoré d\'œuvres artistiques, situé près du jardin botanique de Bruxelles. L\'hôtel dispose de 305 chambres doubles, familiales et suites. Climatisées et munies d\'une connexion Wi-Fi gratuite, elles comprennent une salle de bains avec douche ou baignoire et sèche-cheveux, un minibar, des fauteuils, un coffre-fort, une bouilloire et une télévision satellite. Certaines ont un balcon. Les suites duplex disposent d\'un salon avec canapé et d\'une terrasse.', 93.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/18/17/18176_v10.jpeg'),
(69, 'Novotel Brussels City Centre', 'Bruxelles', 'Belgique', 'Le Novotel Brussels City Centre, reconnaissable à sa tour, est un établissement 4 étoiles situé à une centaine de mètres de la Place Sainte-Catherine. Les 217 chambres sont équipées de la climatisation, d\'un téléviseur avec réception satellite, d\'un mini-bar, d\'un coffre-fort et d\'un espace bureau. La connexion Wi-Fi est accessible dans tout l\'établissement.', 92.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//uploadimages/11/80/11805122.jpeg'),
(70, 'Bedford Hotel & Congress Centre', 'Bruxelles', 'Belgique', 'Parfaitement situé en plein centre de la capitale, le Bedford Hotel & Congress Centre est un établissement trois étoiles à la décoration intérieure assez chic et classique. Toutes les chambres sont dotées d\'un parquet et sont climatisées. La salle de bain est privative et comprend une baignoire. Au sujet de l\'équipement, les logements disposent d\'une télévision à écran plat, d\'un minibar ainsi que d\'un petit bureau de travail. Chaque voyageur bénéfice d\'un accès libre à la salle de fitness.', 65.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/10/62/106256_v8.jpeg'),
(71, 'NH Collection Brussels Centre', 'bruxelles', 'Belgique', 'Bénéficiant d\'une situation idéale au centre de Bruxelles, l\'hôtel NH Collection Brussels Centre est un établissement quatre étoiles avec terrasse sur le toit, parfait pour un séjour confortable dans la capitale belge. L\'hôtel dispose de nombreux types de logements, allant de la chambre simple à la suite pour trois personnes, équipés d\'un plateau de courtoisie, d\'un mini-bar, de la climatisation, et d\'une télévision. ', 121.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/54/55/54556_v13.jpeg'),
(72, 'NH Brugge', 'Bruges', 'Belgique', 'Comportant 4 étoiles, l\'hôtel NH Brugge propose des hébergements dans un ancien monastère du XVIIe siècle dans le centre historique de Bruges. L\'hôtel NH Brugge compte 149 chambres doubles, familiales et suites. Climatisées et dotées d\'une connexion Wi-Fi gratuite, elles comprennent une salle de bains avec sèche-cheveux, un minibar, des fauteuils, un bureau, un nécessaire à thé et café et une télévision satellite. Les suites disposent d\'un salon avec canapé-lit, d\'une machine à café et d\'un coffre-fort.', 90.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/13/87/13873_v6.jpeg'),
(73, 'Martin\'s Brugge', 'Bruges', 'Belgique', 'ouissant d\'une situation géographique exceptionnelle, le Martin\'s Brugge accueille chaque année au cœur de Bruges de nombreux visiteurs venus explorer la Venise du Nord. Les 199 chambres réparties en 6 catégories conviendront à tout type de séjour et sont dotées d\'un TV écran plat, de l\'air conditionné et d\'une salle de bains. ', 81.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//partnerimages/41/65/416537362.jpeg'),
(74, 'Hôtel Aragon', 'Bruges', 'Belgique', 'Lors de votre séjour dans cet hôtel, vous pourrez prendre vos repas dans votre chambre grâce au service d\'étage (horaires limités). L\'établissement vous invite à rejoindre son bar/salon pour une petite pause bien méritée. Un petit déjeuner buffet est servi tous les jours de 07 h 30 à 10 h 30 moyennant un supplément.Le classement officiel des établissements dans ce pays (Belgique) est attribué par Hotelstars Union. Cet établissement a été classé 4 étoiles.Les équipements et services proposés incluent des journaux gratuits dans le hall, un service de nettoyage à sec / blanchisserie et une réception ouverte 24 heures sur 24. Un parking payant sans service de voiturier est disponible dans l\'enceinte de l\'établissement.Les 48 chambres de l\'établissement vous invitent à la détente et comprennent un minibar et une télévision à écran plat. Votre chambre est équipée d\'un lit avec surmatelas préparé avec une couette en duvet d\'oie.', 113.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/54/60/54600_v7.jpeg'),
(75, 'Hotel t Putje', 'Bruges', 'Belgique', 'Profitez de la vue qui vous est offerte depuis une terrasse et des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit et un service d\'assistance pour les visites touristiques ou l\'achat de billets.Le classement officiel des établissements dans ce pays (Belgique) est attribué par Hotelstars Union. Cet établissement a été classé 3 étoiles.Les équipements et services proposés incluent un personnel polyglotte, une consigne à bagages et un coffre-fort à la réception.Les 37 chambres de l\'établissement vous invitent à la détente. L\'accès Wi-Fi à Internet gratuit vous permet de rester en contact avec le reste du monde et votre divertissement est assuré par des chaînes par câble. Une salle de bain privée avec une baignoire ou une douche est à votre disposition.', 51.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/10/72/107205_v5.jpeg'),
(76, 'Univers Hôtel and Brasserie', 'Liège', 'Belgique', 'Si vous souhaitez bénéficier d\'un service remarquable en voyageant, choisissez cet hôtel moderne situé au cœur du quartier des affaires historique de Liège.Le Hotel Best Western Univers est convenablement situé, devant la gare TGV et près des autoroutes, permettant un accès facile à Bruxelles, Anvers, aux Pays-Bas, à l\'Allemagne et à la France. Les clients de l\'hôtel apprécieront la proximité des nombreux sites historiques comme celui de la bataille des Ardennes, dans les Ardennes Belges, ainsi que le Palais des Congrès, les musées et résidences historiques de Liège. Lors d\'un court séjour, découvrez le circuit de F1 de Spa-Francorchamps, situé à seulement 32 kilomètres.', 62.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/14/42/14427_v3.jpeg'),
(77, 'Van Der Valk Sélys Liège Hotel & Spa', 'Liège', 'Belgique', 'Situé en plein centre-ville, dans le coeur historique, culturel et commercial de la Cité Ardente, l’hôtel “Les Comtes de Méan” vous offre tout ce dont vous pouvez rêver en termes de confort.\r\nIl compte au total 125 chambres dont 8 suites particulièrement élégantes, toutes de grande qualité et entièrement équipées.\r\nPlus précisément, l’établissement compte 47 chambres Classic, 16 chambres Classic avec vue, 3 chambres PMR, 51 chambres Deluxe, 7 suites et 1 suite Royale. Les chambres sont situées dans le bâtiment Sauvenière spécialement construit à cet effet et les suites dans l’hôtel particulier de Sélys Longchamps.', 125.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//partnerimages/72/31/723195986.jpeg'),
(78, 'Amosa Liège City Centre Hotel', ' Liège', 'Belgique', 'Situé dans le cœur de Liège, à 5 minutes de marche du Palais des Princes-Évêques et du célèbre Carré, l\'Amosa Liège est un établissement moderne qui vous propose des chambres climatisées, une connexion Wi-Fi gratuite, ainsi qu\'un bar et un restaurant à la carte sur place.\r\n\r\nLes chambres insonorisées de l\'Amosa Liège disposent de parquet et d\'une télévision par câble/satellite à écran plat. Elles comprennent également un dressing et un bureau. Leur salle de bains décloisonnée est quant à elle pourvue d\'une douche, d\'un sèche-cheveux et d\'articles de toilette gratuits.', 101.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/34/08/3408374_v3.jpeg'),
(79, 'nhow Amsterdam RAI', 'Amsterdam ', 'Pays-Bas', 'L\'hôtel nhow Amsterdam RAI est situé dans le quartier des affaires florissant de Zuidas à Amsterdam. Conçu par l\'architecte de renom Reinier de Graaf, l\'hôtel est situé à côté du centre de congrès RAI, avec un accès facile en métro aux principaux sites touristiques d\'Amsterdam. L\'hôtel de 24 étages compte 650 chambres, toutes équipées de baies vitrées avec vue sur la ville. Les 650 chambres récemment construites de l\'hôtel, inspirées des six façades cardinales de l\'hôtel, sont modernes et lumineuses avec de grandes baies vitrées. Les animaux de compagnie sont admis dans les chambres qui sont équipées d\'une machine à café Nespresso, d\'une télévision à écran plat, d\'un coffre-fort numérique, d\'un mini-bar et du Wi-Fi gratuit.', 154.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/15/94/15948718_v4.jpeg'),
(80, 'Hotel NH Amsterdam Centre', 'Amsterdam ', 'Pays-Bas', 'Le NH Amsterdam Centre est un hôtel 4 étoiles qui se trouve à seulement cinq minutes en voiture du célèbre musée Van Gogh dans le quartier culturel d\'Amsterdam. Toutes les chambres sont climatisées et disposent d\'un accès Wi-Fi gratuit, de plateau/bouilloire et de lits extra-longs. Elles possèdent également un minibar et un bureau.', 150.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//uploadimages/17/40/17409694.jpeg'),
(81, 'Pontsteiger', 'Amsterdam', 'Pays-Bas', 'Profitez de la vue qui vous est offerte depuis une terrasse et des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit et un service de concierge.Pour bien finir la journée, vous trouverez sur place un bar / salon. Un petit déjeuner préparé sur commande est servi tous les jours de 07 h 00 à 11 h 00 moyennant un supplément.L\'organisation le comité de tourisme nationale (Pays-Bas) n\'a attribué aucune notation à cet établissement. Pour vous guider, nous vous fournissons une note basée sur notre propre système d\'évaluation.Les équipements et services proposés incluent un service de nettoyage à sec / blanchisserie, une réception ouverte 24 heures sur 24 et une consigne à bagages. Un parking aux horaires limités est disponible dans l\'enceinte de l\'établissement', 95.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/11/32/11321102.jpeg'),
(82, 'Fletcher Amsterdam', ' Amsterdam', 'Pays-Bas', 'La détente avant tout ! Profitez des nombreuses options de loisirs disponibles dans l\'établissement, notamment un service de location de vélos, ou admirez la vue qui vous est offerte depuis une terrasse sur le toit. Parmi les équipements et services offerts par cet hôtel vous trouvez également l\'accès Wi-Fi à Internet gratuit et un service de concierge. Rejoignez les attractions de la région en deux temps trois mouvements grâce à la navette payante.Vous découvrirez de nombreuses spécialités de la cuisine française proposée par Skyrestaurant Pi, l\'un des 2 restaurants de cet hôtel ou profitez du service d\'étage (horaires limités), idéal pour une soirée cocooning en amoureux ou en solo. Si vous avez un petit creux pendant la journée, vous trouverez aussi un café sur place. ', 101.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/25/57/2557474_v4.jpeg'),
(83, 'NH Berlin Alexanderplatz', 'Berlin', 'Allemagne', 'Trouvant l\'équilibre entre un refuge paisible, reposant et une destination animée pour le commerce, l\'hôtel NH Berlin Alexanderplatz possède 225 chambres récemment décorées dans le centre de la ville dynamique de Berlin. À quelques minutes de marche, les hôtes peuvent accéder aux principaux centres de transport, points d\'entrée pour les visites et les attractions de Berlin.', 79.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/13/02/13026_v8.jpeg'),
(84, 'Holiday Inn Berlin City East-Landsberger', 'Berlin', 'Allemagne', 'Offrez-vous un séjour à l\'hôtel Holiday Inn Berlin City East-Landsberger Allee, idéalement situé à 15 minutes en voiture du centre de Berlin.\r\nL\'équipe de la réception vous accueillera à votre arrivée dans le hall lumineux de l\'Holiday Inn Berlin City East-Landsberger Allee. L’hôtel dispose d’un vaste parking à proximité de la rue principale animée par laquelle vous pouvez rejoindre le centre cosmopolite de Berlin en 15 minutes à peine. L\'aéroport Berlin Tegel est à 14 km.', 63.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/57/51/5751_v7.jpeg'),
(85, 'NH Berlin Kurfuerstendamm', 'Berlin', 'Allemagne', 'Par sa situation centrale et sa proximité avec la gare de trains express (S-Bahn) de Savignyplatz ainsi qu\'avec la station de métro Uhlandstrasse, l\'hôtel NH Berlin Kurfürstendamm dispose d\'un emplacement de choix pour les voyageurs d\'affaires autant que de loisirs.', 67.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/52/42/52425_v5.jpeg'),
(86, 'NH Collection Berlin Mitte Friedrichstrasse', 'Berlin', 'Allemagne', 'Le NH Collection Berlin Mitte Friedrichstrasse, anciennement appelé NH Collection Berlin Friedrichstrasse, profite d\'un emplacement privilégié, dans l\'un des quartiers les plus prisés de Berlin. À proximité, vous trouverez les principales attractions de la ville, telles que la porte de Brandebourg, le Checkpoint Charlie et le boulevard Unter den Linden. Pour rejoindre le reste de la ville, la station de métro Friedrichstrasse se trouve à quelques pas de l\'hôtel.', 96.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/57/02/5702_v7.jpeg'),
(87, 'ibis Berlin Mitte', 'Berlin', 'Allemagne', 'Profitez d\'un emplacement parfait pour découvrir la capitale grâce à l\'hôtel ibis Berlin Mitte, à 10 minutes à pied d\'Alexanderplatz. Notre hôtel est un point de départ idéal pour vos excursions et pour explorer la vie nocturne berlinoise. Vous êtes ici a u coeur de l\'action. De nombreuses lignes de bus et de train vous permettent de rejoindre rapidement et facilement des destinations environnantes. Détendez-vous dans l\'une de nos 198 chambres, confortablement meublées dans un style moderne.', 63.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/52/24/52248_v7.jpeg'),
(88, 'Club House', 'Rimini', 'Italie', 'La détente avant tout ! Profitez des nombreuses options de loisirs disponibles dans l\'établissement, notamment une piscine extérieure en saison, ou admirez la vue qui vous est offerte depuis une terrasse et un jardin. Parmi les équipements et services offerts par cet hôtel vous trouvez également l\'accès Wi-Fi à Internet gratuit, un service de garde d\'enfants payant et des magasins.Vous êtes gourmand ? cet hôtel vous propose un café pour reprendre quelques forces et si vous préférez le confort de votre chambre, vous pourrez aussi compter sur un service d\'étage (horaires limités) très pratique. Pour bien finir la journée, vous trouverez sur place un bar / salon.', 45.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/21/55/21551_v12.jpeg'),
(89, 'Hotel Laurentia', 'Rome', 'Italie', 'Profitez des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit, un service de concierge et un service de garde d\'enfants payant.Lors de votre séjour dans cet hôtel, vous pourrez prendre vos repas dans votre chambre grâce au service d\'étage (horaires limités). L\'établissement vous invite à rejoindre son bar/salon pour une petite pause bien méritée.Les équipements et services proposés incluent un poste informatique, un service d\'arrivée express et des journaux gratuits dans le hall.Les 45 chambres de l\'établissement vous invitent à la détente et comprennent un réfrigérateur et une télévision à écran plat. L\'accès Wi-Fi à Internet gratuit vous permet de rester en contact avec le reste du monde et votre divertissement est assuré par des chaînes par satellite. ', 100.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/17/23/17232_v2.jpeg'),
(90, 'MiHotel', 'MIlan', 'Italie', 'MiHotel est un hôtel moderne, idéal pour les clients d\'affaires et pour les touristes, situé dans une position stratégique près du centre de la ville et de l\'Aeroport de Linate. L\'hôtel dispose de 57 chambres dont 5 suites, toutes équipées de parquet de bois (dont certaines avec balcon), la climatisation, douche Jacuzzi, écran LCD, connexion Internet Wifi dans chaque chambre et un coffre-fort', 132.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/12/57/1257987_v2.jpeg'),
(91, 'Casa Ponte Sisto', 'Rome', 'Italie', 'Les équipements et services proposés incluent une consigne à bagages, un coffre-fort à la réception et un ascenseur. En échange d\'un supplément, vous pouvez profiter des services d\'une navette vers et depuis l\'aéroport. De plus un parking aux horaires limités se trouve dans l\'enceinte de l\'établissement.Les 6 chambres climatisées de l\'établissement vous invitent à la détente et comprennent une télévision à écran plat. Un accès gratuit au réseau Internet Wi-Fi et câblé vous permet de rester en contact avec le reste du monde et des chaînes par câble assurent votre divertissement. Les salles de bain comprennent une douche et un bidet. Les équipements et services offerts par l\'établissement comprennent un coffre-fort et un bureau.', 80.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/34/08/3408800_v1.jpeg'),
(92, 'Hotel Massimino', 'Anguillara Sabazia', 'Italie', 'Profitez de la vue qui vous est offerte depuis un jardin et des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit et un service d\'organisation de mariages. Rejoignez les attractions de la région en deux temps trois mouvements grâce à la navette gratuite.Les gourmands apprécieront les saveurs généreuses de Massimino, un restaurant qui abrite un bar / salon pétillant. Si vous avez un petit creux, vous trouverez aussi sur place un café. Un petit-déjeuner buffet gratuit est servi tous les jours de 07 h 00 à 10 h 30.Les équipements et services proposés incluent l\'accès à internet gratuit à Internet, un poste informatique et un service d\'arrivée express', 93.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/96/77/967799_v1.jpeg'),
(93, 'Idea Hotel Milano Bicocca', 'Milan', 'Italie', 'Profitez de la vue qui vous est offerte depuis un jardin et des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit et un service d\'assistance pour les visites touristiques ou l\'achat de billets.Lors de votre séjour dans cet hôtel, vous pourrez prendre vos repas dans votre chambre grâce au service d\'étage 24 heures sur 24. L\'établissement vous invite à rejoindre son bar/salon pour une petite pause bien méritée. Un petit-déjeuner buffet est servi tous les jours moyennant un supplément.Les infrastructures suivantes seront indisponibles du 1 juillet 2021 au 1 janvier 2022 (ces dates sont sujettes à modification) : Restaurant(s)Centre de fitnessLes équipements et services proposés incluent un centre d\'affaires, un service de nettoyage à sec / blanchisserie et une réception ouverte 24 heures sur 24', 99.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/14/92/149266_v6.jpeg');
INSERT INTO `hotel` (`id_hotel`, `nom`, `ville`, `pays`, `description`, `prix`, `photo`) VALUES
(94, 'NH Geneva City', 'Genève', 'Suisse', 'Situé dans un quartier paisible et pittoresque tout proche du centre d’affaires, l’hôtel NH Geneva City combine le charme français du 19e siècle à des commodités sophistiquées et modernes. Les voyageurs y trouveront un cadre luxueux, favorable au renouvellement et à la revitalisation, dans des chambres et des suites meublées avec élégance, dont chacune est équipée du Wi-Fi, de chaînes de télévision internationales, de la climatisation à réglage individuelle et de bien d’autres installations.\r\n', 134.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/25/56/25560_v8.jpeg'),
(95, 'Mandarin Oriental Geneva', 'Genève', 'Suisse', 'Passez de purs moments de détente dans l\'incroyable spa de l\'établissement, un centre bien-être qui propose des massages, des soins corporels et des soins du visage. Un sauna et une salle de fitness ouverte 24 heures sur 24 vous attendent pour des moments de pure détente ! Parmi les services et équipements offerts par cet hôtel de style Art déco, vous trouverez aussi l\'accès Wi-Fi à Internet (en supplément), un service de concierge et un service de garde d\'enfants payant.Laissez-vous séduire par les spécialités de la cuisine péruvienne de Yakumanka, l\'un des 2 restaurants de cet hôtel ou profitez du service d\'étage 24 heures sur 24, idéal pour une soirée cocooning en amoureux ou en solo.', 584.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//partnerimages/13/04/130425818.jpeg'),
(96, 'Hotel ibis budget Zurich City West', 'Zurich', 'Suisse', 'L\'hôtel ibis budget Zurich City West est un établissement une étoile doté d\'un intérieur moderne. Les chambres de l\'hôtel ibis budget Zurich City West ont été rénovées et disposent d\'une télévision à écran plat et d\'une connexion Wi-Fi gratuite. Ils ont également un bureau et des chaises et des salles de bains privées. Si vous le souhaitez, vous pourrez emprunter un sèche-cheveux et un fer à repasser à la réception contre une caution de garantie. Cet établissement propose un parking couvert sur place moyennant des frais supplémentaires.', 94.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/29/29/29295_v8.jpeg'),
(97, 'Lai Lifestyle', ' Lenzerheide - Lai', 'Suisse', 'Profitez des nombreux équipements et services qui caractérisent l\'établissement, notamment l\'accès Wi-Fi à Internet gratuit, un local à skis et une salle de réception.L\'établissement vous invite à rejoindre son bar/salon pour une petite pause bien méritée. Un petit-déjeuner buffet gratuit est servi tous les jours de 07 h 30 à 10 h 30.Les équipements et services proposés incluent des journaux gratuits dans le hall, une consigne à bagages et un coffre-fort à la réception.Les 47 chambres climatisées de l\'établissement vous invitent à la détente et comprennent une télévision à écran plat. L\'accès Wi-Fi à Internet gratuit vous permet de rester en contact avec le reste du monde et votre divertissement est assuré par des chaînes par câble.', 177.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/69/61/6961396_v4.jpeg'),
(98, 'Royal Plaza Montreux & Spa', 'Montreux', 'Suisse', 'Situé directement sur les quais de Montreux, le Royal Plaza Montreux & Spa, hôtel 5 étoiles, bénéficie d’un cadre unique offrant une vue panoramique sur le Lac Léman et les Alpes. A seulement 10 minutes à pied de la gare et du centre de Montreux, l’hôtel est facilement accessible. Il dispose de 154 Chambres & Suites, la majorité possédant balcon privé et vue imprenable sur le lac. Un parking souterrain de 135 places ainsi que le wifi gratuit dans tout l’hôtel sont à disposition des clients.', 186.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/28/69/28696_v3.jpeg'),
(99, 'NH Geneva Airport', 'Meyrin', 'Suisse', 'Situé à côté de l\'aéroport de Genève, l\'hôtel NH Geneva Airport est idéal pour les voyages d\'affaires et de loisirs dans la ville renommée de Genève. Nos hôtes bénéficient de l\'atmosphère confortable et décontractée de l\'hôtel, doté d\'un design moderne et élégant, de nombreux services, et d\'un service de transport gratuit à destination et en provenance de l\'aéroport.', 101.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/40/99/40992_v7.jpeg'),
(100, 'NH Luxembourg', ' Luxembourg', ' Luxembourg', 'Situé dans le quartier d\'affaires de Luxembourg, l\'hôtel NH quatre étoiles de Luxembourg offre aux voyageurs ce qui se fait de mieux au monde : la proximité avec l\'aéroport de la région, des liaisons d\'autoroutes pratiques jusqu\'en Belgique, Allemagne et France, ainsi qu\'un grand nombre de curiosités et de possibilités de loisirs proches, comme la place d\'Armes animée, le Musée national d\'art et d\'histoire et le terrain de golf Grand Ducal.', 94.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/93/31/93310_v8.jpeg'),
(101, 'Parc Hotel Alvisse', 'Luxembourg ', 'Luxembourg ', 'L\'Parc Hotel Alvisse est 4 étoiles de Luxembourg qui propose 325 chambres mais aussi des studios appartements pour des séjours longue durée. Chaque chambre est équipée d\'une TV écran plat, d\'un bureau, d\'un mini-bar et d\'un coffre-fort. Les salles de bains disposent d\'un sèche-cheveux et de peignoirs. Les studios appartements ont une cuisine équipée. L\'Parc Hotel Alvisse propose de nombreux services : piscines, sauna, hammam, centre de remise en forme, salle de sport, ... ', 94.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/93/31/93314_v10.jpeg'),
(102, 'Hotel Novotel Suites Luxembourg', 'Luxembourg', 'Luxembourg', 'Faites une pause au Novotel Suites Luxembourg. Cet hôtel 4 étoiles, situé sur le plateau du Kirchberg et proche du centre-ville, est l\'endroit idéal pour vos voyages d\'affaires et vos escapades en week-end. Novotel Suites Luxembourg met à votre dispositi on de vastes suites tout confort de 30m2 modulables et chaleureuses alliant design et confort. Cet hôtel dispose d\'un Bar et d\'une Boutique Gourmande. Faites une pause détente dans la salle de fitness ou découvrez les atouts de la capitale du Grand-Duché\r\n', 94.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/14/72/1472767_v5.jpeg'),
(103, 'Hotel ibis Styles Luxembourg Centre Gare', 'Luxembourg', 'Luxembourg', 'Idéal pour un séjour d\'affaires ou de tourisme à Luxembourg, cet hôtel propose 68 chambres modernes et confortables, un bar agréable et un petit parking souterrain payant. Situé à 200 mètres de la gare principale et à seulement 15 minutes à pied du centre -ville et de la vieille ville, il offre un accès facile à différents quartiers de Luxembourg, comme Kirchberg et la Cloche d\'Or, ainsi qu\'à l\'aéroport de Findel (8 km). La connexion WIFI et la taxe de séjour sont comprises dans le tarif de la chambre.', 94.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/99/23/99230_v8.jpeg'),
(104, 'Hotel Sofitel Luxembourg Le Grand Ducal', 'Luxembourg', 'Luxembourg', 'Surplombant la vallée de la Pétrusse, le Sofitel Luxembourg Le Grand Ducal offre une vue exceptionnelle sur le quartier historique de la ville. C\'est l\'endroit rêvé pour vous plonger dans le charme inénarrable de Luxembourg, tout en profitant d\'un accueil et d\'installations haut de gamme. L\'hôtel est idéalementsitué, en plein centre historique et à seulement 10 minutes de l\'aéroport. En outre, les nombreuses banques, les institutions internationales et la gare desservie par le TGV sont à proximité.', 194.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/34/83/348311_v6.jpeg'),
(105, 'Mandarin Oriental Hyde Park', 'londres', 'Grande-Bretagne', 'Rejoignez le spa de l\'établissement, un centre bien-être qui propose des massages, des soins corporels et des soins du visage, et permettez qu\'on prenne soin de vous. Profitez des nombreuses infrastructures de loisirs offertes par l\'établissement et qui comprennent notamment une piscine couverte, un sauna et une salle de fitness ouverte 24 heures sur 24. Cet hôtel propose également l\'accès Wi-Fi à Internet (en supplément), un service de concierge et un service de garde d\'enfants payant.Laissez-vous séduire par les spécialités de la cuisine française de Bar Boulud, London, l\'un des 3 restaurants de cet hôtel ou profitez du service d\'étage 24 heures sur 24, idéal pour une soirée cocooning en amoureux ou en solo. Dure journée ? L\'établissement abrite 2 bars/lounges, idéal pour un moment de détente', 1397.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/46/32/46322_v6.jpeg'),
(106, 'nhow London', 'Londres', 'Grande-Bretagne', 'Le nhow London ouvrira bientôt ses portes dans le quartier d\'East London, situé entre Hoxton, Islington et Shoreditch. À seulement quelques minutes du « Silicon Roundabout » de Londres et à proximité de la City et d\'attractions telles que Big Ben et le London Eye, l\'hôtel bâti sur huit étages dispose de 190 chambres aménagées dans un style artistique. La station Farringdon ainsi que l\'Ark Conferences et le 99 City Road Conference Center sont situés à proximité. Conçues par le cabinet d\'architecture et de décoration intérieure Project Orange, les chambres mélangent les styles punk et high-tech. Toutes sont équipées d\'une cafetière et d\'une théière, de téléviseurs à écran plat, d\'un mini-bar, d\'un coffre et du Wi-Fi gratuit. Les animaux de compagnie sont acceptés dans les chambres. Tous les jours, nos clients peuvent profiter de nos petits-déjeuners à la carte, et siroter un verre au bar nhow, sur la terrasse ou dans le hall d\'entrée à côté d\'une cheminée électrique somptueuse.', 190.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/12/50/12503654_v2.jpeg'),
(107, 'The Savoy', 'Londres', 'Grande-Bretagne', 'Élégantes, confortables et presque un second chez soi, les chambres et suites du Savoy sont un endroit parfait pour séjourner au cœur de Londres. Honorant les deux esthétiques principales de l\'hôtel, le style édouardien et l\'Art déco, les chambres et suites marient élégamment le traditionnel avec la technologie dernier cri discrète. Le décorateur, Pierre Yves Rochon, a utilisé les meilleurs matériaux, des lustres en verre de Murano et des revêtements muraux en soie au linge de maison italien et aux sols en marbre.', 1141.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/12/71/12715_v8.jpeg'),
(108, 'St James House', 'Londres', 'Grande-Bretagne', 'Passez un séjour comme il se doit dans une des 15 chambres de l\'établissement et profitez des nombreux équipements à votre disposition, notamment une kitchenette avec un grand réfrigérateur/congélateur et une plaque de cuisson. L\'accès Wi-Fi à Internet gratuit vous permet de rester en contact avec le reste du monde et votre divertissement est assuré par une télévision LCD 20 pouces.', 128.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/18/52/1852817_v4.jpeg'),
(109, 'Banyan Tree Tamouda Bay', 'Fnideq', 'Maroc', 'Rejoignez le spa de l\'établissement, un centre bien-être qui propose des massages et des soins du visage, et permettez qu\'on prenne soin de vous. Si vous mettez la détente avant toute autre chose, n\'hésitez pas à profiter des nombreuses infrastructures de loisirs proposées par l\'établissement et qui incluent notamment une piscine extérieure, une piscine couverte et un bain à remous. Parmi les équipements et services offerts par cet hôtel de style méditerranéen, vous trouverez aussi l\'accès Wi-Fi à Internet gratuit, un service de concierge et un service de garde d\'enfants gratuit.Pendant votre séjour, vous vous régalerez à Azura Beach Restaurant, l\'un des 3 restaurants de cet hôtel et profiterez d\'un service d\'étage 24 heures sur 24. Idéal pour une soirée cocooning pleine de saveurs ! ', 334.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/51/74/5174494_v3.jpeg'),
(110, 'Hotel Riu Tikida Palmeraie -  All Inclusive', 'Marrakech', 'Maroc', 'Offrant une vue exceptionnelle sur un jardin exotique, avec en arrière-plan les sommets de l\'Atlas, l\'hôtel Hotel Riu Tikida Palmeraie -  All Inclusive est un établissement certifié quatre étoiles. Les 350 chambres/suites climatisées sont réparties dans cinq bâtiments. Toutes sont équipées d\'un coffre-fort, d\'un minibar et d\'une télévision à écran plat. La décoration y est assez sobre, avec la présence d\'un balcon ou d\'une terrasse. La salle de bain est privative, décorée avec du marbre. L\'établissement propose gratuitement des navettes pour rejoindre le centre-ville. La connexion Wi-Fi est en illimitée. Une salle de sport et le Tikida spa (piscine, spa, massages) sont à disposition. Une piscine extérieure est également intégrée. Un petit-déjeuner buffet américain est servi chaque matin. Pour déjeuner/dîner, l\'hôtel dispose de trois restaurants dont deux qui concoctent une cuisine marocaine ou italienne. Trois bars sont localisés dans l\'établissement. L\'hôtel Hotel Riu Tikida Palmeraie -  All Inclusive permet de rejoindre en voiture le centre-ville et la place Jemaa el-Fna en moins de 20 minutes. L\'aéroport est distant de 12 kilomètres.', 86.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/98/00/980085_v4.jpeg'),
(111, 'Kenzi Club Agdal Médina', 'Marrakech', 'Maroc', 'Le Kenzi Club Agdal Médina est un hôtel cinq étoiles proposant une formule « tout compris », avec piscines et courts de tennis, situé à environ six kilomètres du centre de Marrakech. Les 310 chambres (réparties en Deluxe, chambres familiales et Suites Junior) disposent toutes d\'un balcon ou d\'une terrasse, de la climatisation, d\'un frigo, d\'une télé écran plat et d\'une connexion Wi-Fi gratuite. Le Kenzi Club Agdal Médina possède quatre piscines, dont une avec toboggans et une pour enfants, un spa (en supplément), une navette vers le centre, une équipe d\'animation et plusieurs activités et espaces de loisirs. La formule « tout compris » permet aux hôtes de se restaurer à volonté dans deux espaces différents (l\'un ouvert le soir uniquement) et de profiter de deux bars. La place Jemaa-el-Fna, la Médina, le mosquée de Koutoubia et le palais de la Bahia sont tous situés à plus ou moins six kilomètres du complexe.', 173.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/14/72/1472225_v6.jpeg'),
(112, 'Opera Plaza Marrakech', 'Marrakech', 'Maroc', 'L’Opera Plaza Marrakech et ses quatre étoiles vous accueillent dans un cadre luxueux et authentique. Situé à proximité immédiate de la gare de Marrakech et du théâtre royal, l’établissement convient aussi bien aux touristes qu’aux voyageurs d’affaires.\r\nLes chambres de l’hôtel sont soigneusement décorées dans une ambiance chic traditionnelle et comprennent un coin salon, un téléviseur à écran plat et une salle de bains privative.', 66.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/27/35/2735153_v3.jpeg'),
(113, 'Fairmont Royal Palm Marrakech', 'Marrakech', 'Maroc', 'Au coeur d’une oliveraie centenaire, sur une terre ocre dominée par les sommets enneigés de l’Atlas et à 12 km de l’effervescente médina de Marrakech, le Fairmont Royal Palm Marrakech est un lieu de vie exclusif à la fois hôtelier et golfique.Le Fairmont Marrakech vous invite à la rencontre de l’authenticité de la culture locale et de l’enchantement d’un conte. Pour mieux se retrouver, se ressourcer, grâce à l’harmonie réussie d’un lieu paradisiaque et d’un service associant élégance et simplicité.', 441.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/95/04/9504106_v6.jpeg'),
(114, 'Royal Tulip City Center Tanger', 'Tanger', 'Maroc', 'Besoin d\'un emplacement idéal pour votre séjour ? L\'hôtel Royal Tulip City Center Tanger convention & Spa, situé en plein centre-ville, signe la parfaite alliance entre confort et efficacité, le plus sophistiqué de la région. Avec un style et élégance uniques. L’hôtel propose 216 chambres élégantes avec vue sur mer, fontaine et parc. \r\n', 128.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/35/05/3505368.jpeg'),
(115, 'La Mamounia', 'Marrakech', 'Maroc', 'Niché dans un ancien parc royal de Marrakech, La Mamounia est un hôtel cinq étoiles alliant luxe et prestige. L\'hôtel propose 135 chambres et 71 suites, ainsi que 3 riads. Climatisées et dotées d\'une connexion Wi-Fi gratuite, les chambres possèdent une salle de bains et une télévision satellite. Certaines ont un balcon. Les suites comprennent une chambre et un ou deux salons. Les riads comptent une cuisine, un salon, trois chambres, un patio et une piscine. Doté d\'une piscine extérieure et d\'un jardin, La Mamounia comprend un spa avec piscine, un spa privé, un espace fitness, des salles de réunion, des courts de tennis et un parking gratuit. ', 642.00, 'https://imgcy.trivago.com/d_dummy.jpeg,f_auto,q_auto/if_iw_lte_ih,c_scale,w_236/if_else,c_scale,h_160/e_improve,q_auto:low//partnerimages/32/15/321549602.jpeg'),
(116, 'Holiday Inn Express Dubai - Safa Park', ' Dubaï', 'Émirats arabes unis', 'Détendez-vous dans la fraîcheur de l\'hôtel climatisé Holiday Inn Express Dubai-Safa Park, situé sur l’artère principale de Dubaï, à 15 minutes en voiture de son aéroport international.Prenez la navette à l’aéroport et descendez la rue Sheik Zayed en direction de l’hôtel Holiday Inn Express Dubai-Safa Park et son emblème d’un vert éclatant. Avec son éclairage tamisé et ses divans moelleux, le hall donne le ton. Le service de bus gratuit vous emmènera à la plage bordée de palmiers de Jumeirah en 10 minutes, après avoir pris un petit-déjeuner continental au buffet, également offert.En sortant de l’hôtel ', 123.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/89/76/897635_v4.jpeg'),
(117, 'Rove Dubai Marina', 'Dubaï', 'Émirats arabes unis', 'N\'hésitez pas à profiter des nombreuses infrastructures de loisirs à disposition et qui incluent notamment une piscine extérieure et une salle de fitness ouverte 24 heures sur 24. Parmi les équipements et services offerts par cet hôtel vous trouvez également l\'accès Wi-Fi à Internet gratuit, une salle de jeux vidéo et un service d\'assistance pour les visites touristiques ou l\'achat de billets.Pendant votre séjour dans cet hôtel, profitez du restaurant qui propose le déjeuner et le dîner. Pour vos petits creux, l’établissement offre également un café et un service d\'étage (horaires limités). Un petit déjeuner continental est servi tous les jours de 06 h 30 à 11 h 30 moyennant un supplément.Les équipements et services proposés incluent un centre d\'affaires, un service de nettoyage à sec / blanchisserie et une réception ouverte 24 heures sur 24. ', 117.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/97/12/9712430_v1.jpeg'),
(118, 'Holiday Inn Dubai Al-maktoum Airport', 'Émirats arabes unis', 'Dubaï', 'Rejoignez le spa de l\'établissement, un centre bien-être qui propose des massages, et permettez qu\'on prenne soin de vous. L\'établissement vous invite à la détente et propose de nombreuses infrastructures de loisirs, notamment une piscine extérieure et un sauna. Parmi les équipements et services offerts par cet hôtel vous trouvez également l\'accès Wi-Fi à Internet gratuit, un service de concierge et une boutique de souvenirs/un kiosque à journaux.Cet hôtel abrite un délicieux restaurant, Flying Cups et un café. Détendez-vous devant un verre au bar en bord de piscine ou dans un des 2 bars/lounges de l\'établissement. Un petit déjeuner buffet est servi en semaine de 06 h 30 à 10 h 30 et le week-end de 06 h 30 à 11 h 00 (en supplément).Les équipements et services proposés incluent un centre d\'affaires ouvert 24 heures sur 24, des journaux gratuits dans le hall et un service de nettoyage à sec / blanchisserie. Si vous devez organiser une réunion à Dubaï, faites confiance à cet hôtel qui dispose d\'espaces événements mesurant 460 mètres carrés et comprenant un centre de conférence', 103.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/19/12/19120502_v1.jpeg'),
(119, 'Oaks Ibn Battuta Gate Dubai', 'Dubaï', 'Émirats arabes unis', 'Passez de purs moments de détente dans l\'incroyable spa de l\'établissement, un centre bien-être qui propose des massages, des soins corporels et des soins du visage. Non seulement vous pouvez vous faire bronzer sur la plage privée, mais vous pouvez également profiter des nombreuses infrastructures de loisirs à votre disposition, notamment une discothèque et un centre de remise en forme. Parmi les équipements et services offerts par cet hôtel vous trouvez également l\'accès Wi-Fi à Internet gratuit, un service de concierge et une boutique de souvenirs/un kiosque à journaux. Une navette gratuite vous conduit jusqu\'à la plage.De délicieuses spécialités internationales vous attendent à Mistral, un restaurant qui abrite un bar / salon, parfait pour prendre l\'apéritif avant le dîner. Si vous préférez une soirée cocooning, un service d\'étage 24 heures sur 24 est à votre disposition. L\'établissement vous invite à rejoindre son bar en bord de piscine pour une petite pause bien méritée. Un petit déjeuner buffet est servi en semaine de 07 h 00 à 10 h 30 et le week-end de 07 h 00 à 11 h 00 (en supplément)', 174.00, 'https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_450,q_auto,w_450/itemimages/16/39/1639817_v6.jpeg');

-- --------------------------------------------------------

--
-- Structure de la table `reco`
--

DROP TABLE IF EXISTS `reco`;
CREATE TABLE IF NOT EXISTS `reco` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_hotel` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `reco`
--

INSERT INTO `reco` (`id`, `id_hotel`) VALUES
(1, 35),
(2, 76),
(3, 53),
(4, 87),
(5, 45),
(6, 78),
(7, 1),
(8, 1),
(9, 1),
(10, 1),
(11, 1),
(12, 118),
(13, 117),
(14, 33);

-- --------------------------------------------------------

--
-- Structure de la table `reservation`
--

DROP TABLE IF EXISTS `reservation`;
CREATE TABLE IF NOT EXISTS `reservation` (
  `id_reservation` int(11) NOT NULL AUTO_INCREMENT,
  `id_utilisateur` int(11) NOT NULL,
  `id_hotel` int(11) NOT NULL,
  PRIMARY KEY (`id_reservation`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `reservation`
--

INSERT INTO `reservation` (`id_reservation`, `id_utilisateur`, `id_hotel`) VALUES
(2, 17, 117),
(3, 12, 117),
(4, 12, 1),
(5, 12, 1),
(6, 12, 1),
(7, 12, 1),
(8, 12, 1),
(9, 12, 1),
(10, 12, 1),
(11, 12, 1),
(12, 12, 1),
(13, 12, 1),
(14, 12, 1);

-- --------------------------------------------------------

--
-- Structure de la table `utilisateur`
--

DROP TABLE IF EXISTS `utilisateur`;
CREATE TABLE IF NOT EXISTS `utilisateur` (
  `id_utilisateur` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(100) DEFAULT NULL,
  `prenom` varchar(100) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `mdp` varchar(2000) NOT NULL,
  `administrateur` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_utilisateur`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `utilisateur`
--

INSERT INTO `utilisateur` (`id_utilisateur`, `nom`, `prenom`, `email`, `mdp`, `administrateur`) VALUES
(12, 'deronne', 'jules', 'jules.deronne@gmail.com', '$argon2i$v=19$m=65536,t=5,p=1$DSqZX1BZhI9zLUwlXdUBAW54K52EinhCurfZROeAdjAPZH19iUBMAsCX3bn9rkEhiN03Xcd+pHiT+SyrGaimk0c37xSHm1OyqOjBOxDMXVzCjc7X2QZxpkQDRSAVyl5jSIAkw/Jk1SgoVcOShg0gXZix51YKW40Qm4ZuluT10as$Ojv0zFb/yskAVq0rKCmzC4RfARjadSh9Q9bAqxS7ZC2pU/OGx1WNiIDePRT4lBSVz6KwU/rkq6raoaRErPm2jeimkZ/3jAUq6aKiusEfyyCSvJoIzSslkKjIxK0gy+ymjBYYbd/QV0F7rHtDEzaCdwHI1287UCv0fJoy/9qHid8', 0),
(17, 'Admin', 'Admin', 'Admin@gmail.com', '$argon2i$v=19$m=65536,t=5,p=1$h9diaWfG7ypWXybjqX480pt+b31iPusbtxeoi/pyVFi/Vx+G1+CvlWvcJC1eOkkgr4ZxEDscfBwbuMrx7/pQej5U9qdWap2iEEuewIPn+XLjhWCZX8vDnehOUNzcRBwd1qhKIZu+gnnHdjE3c1mxY++cqmKQCSUo8VdZnLZLb34$q3UXH0zrrn8EfEanyf9I+2J3EaNP7Vf8YQ1qGVBOPfiZfw0I4aFaH/NCtqHbGqaHINa/5GXq4NPc94cRL4oFwH+bCPbCfp6cFVSxTodZe2DumfqlVSFby9g2jLqgVNPg6E8wHUEJ9TJO9R5FSDSBdv6CfLqmyb/L40xr0EO7RdE', 1);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
